version: '3.8'
services:
  backend:
    build: ./backend
    container_name: orcamento-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - orcamento-net
  db:
    image: mysql:8.0
    container_name: orcamento-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orcamento
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - orcamento-net
volumes:
  db_data:
networks:
  orcamento-net:
    driver: bridge
